### ISSUE TITLE
Can't see Like count for own posts

### ISSUE THREAD

**Issue by Kretol** [JN-Jones/MyLikes#3]
Hello!

I just recently installed this plugin on a new upgraded forum (to 1.8.3).  I imported the like count I already had (using the thankyou-like plugin) to the reputation table, and it seems everything was imported fine.  However, I don't see a Like count for any of my posts.  Is there an option to enable this, or would it be possible to create an option so that post authors can at least see the like count for their own posts?

Thank you!

**Comment by JN-Jones** [comment]
This has already been fixed in the `jonescore` branch

**Comment by Kretol** [comment]
Ah.  Thank you!
